spring:
  application:
    name: reservation-service
  datasource:
    username: dev_postgres
    password: devpg123
    url: jdbc:postgresql://172.15.100.240:5432/dev_postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-timeout: 30000  # 30 seconds
      idle-timeout: 6000000      # 100 minutes
      max-lifetime: 300000      # 5 minutes

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: reservation

server:
  port: 3008
  servlet:
    context-path: /rs

debug: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%highlight(%-5level)) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: info


springdoc:
  swagger-ui:
    config-url: /rs/v3/api-docs/swagger-config
    url: /rs/v3/api-docs
