spring:
  application:
    name: reservation-service
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-timeout: 30000  # 30 seconds
      idle-timeout: 6000000      # 100 minutes
      max-lifetime: 300000      # 5 minutes
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: medi-track-cmm707:us-central1:medi-track-sql

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: reservation
  profiles:
    active: gcp

server:
  port: 3008
  servlet:
    context-path: /rs

debug: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%highlight(%-5level)) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: info


springdoc:
  swagger-ui:
    config-url: /rs/v3/api-docs/swagger-config
    url: /rs/v3/api-docs
