spring:
  datasource:
    url: jdbc:postgresql:///postgres
    username: postgres
    password: root
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: medi-track-cmm707:us-central1:medi-track-sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
