spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=reservation
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

