spring:
  datasource:
    url: jdbc:postgresql://medi-track.cfw6m8ce6t0w.us-east-1.rds.amazonaws.com:5432/medi_track?currentSchema=reservation
    username: postgres
    password: M*A&5HQ%v;jKHU$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

